# Generated by Django 4.1.1 on 2022-09-12 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tamu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('namaInstansi', models.CharField(max_length=255)),
                ('jaminan', models.CharField(max_length=255)),
                ('keperluan', models.TextField()),
                ('namaKaryawan', models.CharField(max_length=255)),
                ('jumlahTamu', models.IntegerField(default=1)),
                ('foto', models.ImageField(upload_to='')),
                ('waktu', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Guest',
                'db_table': 'Tamu',
            },
        ),
    ]
