# Generated by Django 4.1.1 on 2022-09-12 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_tamu_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tamu',
            name='foto',
            field=models.ImageField(upload_to='images'),
        ),
    ]
